# Generated by Django 4.1.6 on 2023-05-11 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='custom_images/no_image.jpg', upload_to='category_images/'),
        ),
    ]
